      * ###################################
      * ### Autor: Eduardo Pozos Huerta ###
      * ### Datum: 17. August. 2026     ###
      * ### Aktua: 17. August. 2026     ###
      * ### Lizenz: MIT                 ###
      * ###################################

           SELECT OPTIONAL BANK-ACCOUNT-DATA-FILE
           ASSIGN TO "account.db"
           ORGANIZATION IS INDEXED
           ACCESS IS RANDOM
           RECORD KEY IS KSDS-BANK-ACCOUNT-NUMBER
           ALTERNATE RECORD KEY IS KSDS-BANK-FISCAL-ID
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-GOV-TYPE
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-BANK-TYPE
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-OWNER-FULL-NAME
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-OWNER-FISCAL-ID
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-OWNER-GOV-ID
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-CURRENCY
           ALTERNATE RECORD KEY IS KSDS-BANK-ACCOUNT-CURRENCY-MOUNT
           FILE STATUS IS WS-BANK-ACCOUNT-FILE-STATUS.