###################################
### Autor: Eduardo Pozos Huerta ###
### Datum: 17. August. 2026     ###
### Aktua: 17. August. 2026     ###
### Lizenz: MIT                 ###
###################################

##################
### Main Rules ###
##################

all: object libraries executable

compile: object libraries executable

install:
	install $(BINARY_LIBRARY_STATIC_RCBS_ACCOUNT)
	install $(BINARY_LIBRARY_STATIC_RCBS_REGISTER)
	install $(BINARY_LIBRARY_STATIC_RCBS_TRANSACTION)
	install $(BINARY_LIBRARY_SHARED_VERSION_RCBS_ACCOUNT)
	install $(BINARY_LIBRARY_SHARED_VERSION_RCBS_REGISTER)
	install $(BINARY_LIBRARY_SHARED_VERSION_RCBS_TRANSACTION)
	install $(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_ACCOUNT)
	install $(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_REGISTER)
	install $(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_TRANSACTION)
	install $(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_ACCOUNT)
	install $(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_REGISTER)
	install $(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_TRANSACTION)
	install $(BINARY_EXECUTABLE_RCBS)

###############
### Running ###
###############

run: $(BINARY_EXECUTABLE_RCBS)
	@./$<

debug: $(BINARY_EXECUTABLE_RCBS)
	@gdb ./$<

#################
### Cleaning ###
#################

clean:
	rm -f $(shell find $(BUILDDIR)/object -type f -name '*.o')

distclean:
	rm -rf $(BUILDDIR)

###################
### Depen Rules ###
###################

object: $(OBJECT_FILES_SYSTEM_ACCOUNT) $(OBJECT_FILES_SYSTEM_REGISTER) $(OBJECT_FILES_SYSTEM_TRANSACTION)
libraries: \
	$(BINARY_LIBRARY_STATIC_RCBS_ACCOUNT)           $(BINARY_LIBRARY_STATIC_RCBS_REGISTER)           $(BINARY_LIBRARY_STATIC_RCBS_TRANSACTION) \
	$(BINARY_LIBRARY_SHARED_VERSION_RCBS_ACCOUNT)   $(BINARY_LIBRARY_SHARED_VERSION_RCBS_REGISTER)   $(BINARY_LIBRARY_SHARED_VERSION_RCBS_TRANSACTION) \
	$(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_ACCOUNT) $(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_REGISTER) $(BINARY_LIBRARY_SHARED_SOVERSION_RCBS_TRANSACTION) \
	$(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_ACCOUNT)   $(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_REGISTER)   $(BINARY_LIBRARY_SHARED_SYMLINK_RCBS_TRANSACTION)

executable: $(BINARY_EXECUTABLE_RCBS)