      * ###############################
      * ### Autor: Reymon Dev       ###
      * ### Datum: 17. August. 2026 ###
      * ### Aktua: 17. August. 2026 ###
      * ### Lizenz: MIT             ###
      * ###############################

           SELECT OPTIONAL TRANSACTION-DF
           ASSIGN TO LK-TRANSACTION-DF
           ORGANIZATION IS INDEXED
           ACCESS IS DYNAMIC
           RECORD KEY IS RK-TRANSACTION-ID

           ALTERNATE RECORD KEY IS ARK-TRANSACTION-TYPE

           ALTERNATE RECORD KEY IS ARK-TRANSACTION-ORIGIN-ACCOUNT-FID
           ALTERNATE RECORD KEY IS ARK-TRANSACTION-RECEIVE-ACCOUNT-FID
           
           ALTERNATE RECORD KEY IS ARK-TRANSATCION-ORIGIN-BANK-FID
           ALTERNATE RECORD KEY IS ARK-TRANSATCION-RECEIVE-BANK-FID

           ALTERNATE RECORD KEY IS ARK-TRANSACTION-ORIGIN-CURRENCY
           ALTERNATE RECORD KEY IS ARK-TRANSACTION-RECEIVE-CURRENCY

           ALTERNATE RECORD KEY IS ARK-TRANSACTION-ORIGIN-COUNTRY
           ALTERNATE RECORD KEY IS ARK-TRANSACTION-RECEIVE-COUNTRY

           ALTERNATE RECORD KEY IS ARK-TRANSACTION-AMOUNT
           
           FILE STATUS IS WS-TRANSACTION-FST.